from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


def test_read_root():
    """Verify that the API root/health check is accessible."""
    response = client.get("/")
    assert response.status_code == 200
    assert "status" in response.json()


def test_proactive_notify_auth():
    """Verify that the notify endpoint requires authentication (if implemented) or at least exists."""
    response = client.post(
        "/api/notify", json={"user_id": "test_user", "message": "Hello from test", "priority": "high"}
    )
    # If it returns 401/403, that's also a valid test of security
    assert response.status_code in [200, 401, 403, 405, 422]


def test_create_approval_plan_explicit_id():
    """Verify creating an approval plan with an explicit plan_id."""
    import uuid

    plan_id = f"heal_exp_{uuid.uuid4().hex[:8]}"
    payload = {
        "plan_id": plan_id,
        "requester_id": "fsirio",
        "requester_telegram_id": "963420066",
        "title": "Fix memory leak",
        "plan_details": "Details about memory leak fix",
        "task": "Restart service and tune GC",
        "target_project": "homelab",
    }
    response = client.post("/api/plans", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "success"
    assert data["plan_id"] == plan_id


def test_create_approval_plan_autogenerated_id():
    """Verify creating an approval plan with autogenerated plan_id starting with heal_."""
    payload = {
        "requester_id": "fsirio",
        "requester_telegram_id": "963420066",
        "title": "Fix disk space",
        "plan_details": "Prune unused docker images",
        "task": "docker system prune -f",
        "target_project": "homelab",
    }
    response = client.post("/api/plans", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "success"
    assert data["plan_id"].startswith("heal_")
